const dataSurvey = document.getElementById('data-survey')
dataSurvey.setAttribute('style', 'display: flex; flex-direction: column; gap: 10px; font-family: arial;')

const name = document.createElement('div')
name.setAttribute('style', 'display: flex; flex-direction: column; font-weight: bold; color: blue;')
const labelName = document.createElement('label')
const inputName = document.createElement('input')
labelName.textContent = 'Siapa nama Anda?'
labelName.setAttribute('for', 'name')
inputName.setAttribute('type', 'text')
inputName.setAttribute('id', 'name')
inputName.setAttribute('style', 'width: 20%')
inputName.setAttribute('placeholder', 'Nama')
name.appendChild(labelName)
name.appendChild(inputName)
dataSurvey.appendChild(name)

const age = document.createElement('div')
age.setAttribute('style', 'display: flex; flex-direction: column; font-weight: bold; color: blue;')
const labelAge = document.createElement('label')
const inputAge = document.createElement('input')
labelAge.textContent = 'Berapa umur Anda?'
labelAge.setAttribute('for', 'age')
inputAge.setAttribute('type', 'text')
inputAge.setAttribute('id', 'age')
inputAge.setAttribute('style', 'width: 20%')
inputAge.setAttribute('placeholder', 'Umur')
age.appendChild(labelAge)
age.appendChild(inputAge)
dataSurvey.appendChild(age)


const boxGender = document.createElement('div')
const gender = document.createElement('div')
const choice = document.createElement('div')
const labelGenderMale = document.createElement('label')
const inputGenderMale = document.createElement('input')
const labelGenderFemale = document.createElement('label')
const inputGenderFemale = document.createElement('input')
gender.textContent = 'Apa jenis kelamin Anda?'
gender.setAttribute('style', 'font-weight: bold; color: blue;')
labelGenderMale.textContent = 'Laki-laki'
labelGenderMale.setAttribute('for', 'male')
inputGenderMale.setAttribute('type', 'radio')
inputGenderMale.setAttribute('id', 'male')
inputGenderMale.setAttribute('name', 'gender')
labelGenderFemale.textContent = 'Perempuan'
labelGenderFemale.setAttribute('for', 'female')
inputGenderFemale.setAttribute('type', 'radio')
inputGenderFemale.setAttribute('id', 'female')
inputGenderFemale.setAttribute('name', 'gender')
choice.appendChild(inputGenderMale)
choice.appendChild(labelGenderMale)
choice.appendChild(inputGenderFemale)
choice.appendChild(labelGenderFemale)
boxGender.appendChild(gender)
boxGender.appendChild(choice)
dataSurvey.appendChild(boxGender)

const boxSmoke = document.createElement('div')
const smoke = document.createElement('div')
const smokeChoice = document.createElement('div')
const labelYes = document.createElement('label')
const inputYes = document.createElement('input')
const labelNo = document.createElement('label')
const inputNo = document.createElement('input')
smoke.textContent = 'Apakah Anda perokok?'
smoke.setAttribute('style', 'font-weight: bold; color: blue;')
labelYes.textContent = 'Iya'
labelYes.setAttribute('for', 'yes')
inputYes.setAttribute('type', 'radio')
inputYes.setAttribute('id', 'yes')
inputYes.setAttribute('name', 'smoke')
labelNo.textContent = 'Tidak'
labelNo.setAttribute('for', 'no')
inputNo.setAttribute('type', 'radio')
inputNo.setAttribute('id', 'no')
inputNo.setAttribute('name', 'smoke')
smokeChoice.appendChild(inputYes)
smokeChoice.appendChild(labelYes)
smokeChoice.appendChild(inputNo)
smokeChoice.appendChild(labelNo)
boxSmoke.appendChild(smoke)
boxSmoke.appendChild(smokeChoice)
dataSurvey.appendChild(boxSmoke)

const trySmoke = document.createElement('div')
const textSmoke = document.createElement('div')
const brandSmoke = document.createElement('div')
const brand1 = document.createElement('div')
const brand2 = document.createElement('div')
const brand3 = document.createElement('div')
const brand4 = document.createElement('div')
const label1 = document.createElement('label')
const input1 = document.createElement('input')
const label2 = document.createElement('label')
const input2 = document.createElement('input')
const label3 = document.createElement('label')
const input3 = document.createElement('input')
const label4 = document.createElement('label')
const input4 = document.createElement('input')
textSmoke.textContent = 'Jika Anda perokok, rokok apa yang Anda pernah coba?'
textSmoke.setAttribute('style', 'font-weight: bold; color: blue;')
label1.textContent = 'Gudang Garam Filter'
label1.setAttribute('for', 'gg-filter')
input1.setAttribute('type', 'checkbox')
input1.setAttribute('id', 'gg-filter')
label2.textContent = 'Lucky Strike'
label2.setAttribute('for', 'strike')
input2.setAttribute('type', 'checkbox')
input2.setAttribute('id', 'strike')
label3.textContent = 'Marlboro'
label3.setAttribute('for', 'marlboro')
input3.setAttribute('type', 'checkbox')
input3.setAttribute('id', 'marlboro')
label4.textContent = 'Esse'
label4.setAttribute('for', 'esse')
input4.setAttribute('type', 'checkbox')
input4.setAttribute('id', 'esse')
brand1.appendChild(input1)
brand1.appendChild(label1)
brand2.appendChild(input2)
brand2.appendChild(label2)
brand3.appendChild(input3)
brand3.appendChild(label3)
brand4.appendChild(input4)
brand4.appendChild(label4)
brandSmoke.appendChild(brand1)
brandSmoke.appendChild(brand2)
brandSmoke.appendChild(brand3)
brandSmoke.appendChild(brand4)
trySmoke.appendChild(textSmoke)
trySmoke.appendChild(brandSmoke)
dataSurvey.appendChild(trySmoke)